### ISSUE TITLE
how to get a version to show on pkg.go.dev

### ISSUE THREAD

**Issue by jba** [westphae/geomag#2]
Hi, pkg.go.dev maintainer here. This is a response to your anonymous feedback from February 8. Apologies for the delay.

We get all our module information from the proxy (proxy.golang.org). So whenever you or anyone else `go get`s a version of your module through the proxy (which is the default setting for `go get`), then we'll soon see it and process it.

So if you just run `go get github.com/westphae/geomag@v1.0.2`, it should show up on pkg.go.dev shortly.

We're working on a better system, where you can click a button on the site to fetch a new version.

**Comment by westphae** [comment]
Thank you!  I'll give that a try.

**Comment by westphae** [comment]
Closed.  Worked great.  Thanks for the response!
